version: '2'
services:
  wlb-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/wlb/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wlb
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
